### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by grantland** [BoltsFramework/Bolts-Android#109]
https://github.com/BoltsFramework/Bolts-Android/milestones/1.4.0

- [x] #99 Support partial waits
- [x] #100 Monitor for unobserved errors
- [X] #106 Return a `Task` with an `ExecutorException` when an exception occurs in an executor
